# Config file for automatic testing at travis-ci.org
sudo: required
dist: xenial
language: python
cache:
  - pip
  - npm
  - docker

services:
  - docker

language: python
python:
  - 3.7
  - 3.6

env:
  global:
    secure: Ayptpj0DwwR+c5s6NGWEmwcSdAcH8CmF0si3xFFJP7yY9Ln6098AXpenGwU7GLKIukIe99+noSl3hTwPa8WiNFdrHPmkEGQMnylTCDnBZTvnVvruzNYhJn4oCP8ZHW5mmUxXZoXKzvf76MAjunbHiJKrVofKspbm2lsjZniF9gHSQdVzIaz5QmU1NptIvNGLzNEBE3I5L1NQZBRQpLvouseAGqjweO3y2h4nOGd7Nr4WLeNAOv9J8seVzSmAXRihiXPK6UzLZ8Tn+QCpAoAlpabzn2e3B2X94vsYGckwvB1/wuIt8OYBRV0Cn7ub8AegW+rjW4QMoVZ7cIEPh/qJBZxLhO752crY1bq2DnxzyMr7eDZlthfdxrlWYoiMH26wxGJk0Aa028VKm+pvqNtSAMLxXKVmQ/FiPousbBK05U+71OJYzA4wRCvsE/xGsCpwBH56PDEPXOFX51G+YEEdqpmrFO3MH5f6xEm/TbuzlL1z+gekJgDZndpjPQybQB1vfIlSIGNv2QbBIRF4U4tTxCBa7PSXcEvtOWpI+FIki7h5Dhnhm5HFQGYtcIBVkogNH9VXR1LaR2JDcmI29+MaxDTyCnVpXry7S8/SZPTlGxsvzF57ucajJ5ktZyY1cAgmV+5ZSFFAJHHj04aCZwD7j6RDCmec1FtTdchP3ibwLH4=


  matrix:
    - DJANGO="1.11" CMS="3.4"
    - DJANGO="1.11" CMS="3.5"
    - DJANGO="1.11" CMS="3.6"
    - DJANGO="1.11" CMS="3.7"
    - DJANGO="2.0"  CMS="3.6"
    - DJANGO="2.0"  CMS="3.7"
    - DJANGO="2.1"  CMS="3.6"
    - DJANGO="2.1"  CMS="3.7"
    - DJANGO="2.2"  CMS="3.7"

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env:
        - DJANGO="1.11" CMS="3.4"
    - python: 2.7
      env:
        - DJANGO="1.11" CMS="3.5"
    - python: 2.7
      env:
        - DJANGO="1.11" CMS="3.6"
    - python: 2.7
      env:
        - DJANGO="1.11" CMS="3.7"
    - python: 3.5
      env:
        - DJANGO="1.11" CMS="3.4"
    - python: 3.5
      env:
        - DJANGO="1.11" CMS="3.5"
    - python: 3.5
      env:
        - DJANGO="1.11" CMS="3.6"
    - python: 3.5
      env:
        - DJANGO="1.11" CMS="3.7"
    - python: 3.5
      env:
        - DJANGO="2.0" CMS="3.6"
    - python: 3.5
      env:
        - DJANGO="2.0" CMS="3.7"
    - python: 3.5
      env:
        - DJANGO="2.1" CMS="3.6"
    - python: 3.5
      env:
        - DJANGO="2.1" CMS="3.7"

    - python: 3.6
      env: TOXENV=flake8
      before_install:
        - echo "skip before_install"
      after_success:
        - echo "skip after_success"

    - python: 3.6
      env: TOXENV=docs-create
      before_install:
        - echo "skip before_install"
      after_success:
        - echo "skip after_success"

    - python: 3.6
      env: TOXENV=docs-links
      before_install:
        - echo "skip before_install"
      after_success:
        - echo "skip after_success"

    - stage: deploy
      name: PiPy-release
      if: type == push AND tag IS present
      install: echo "skip install"
      before_script: echo "skip before_script"
      script: echo "skip install"
      after_success: echo "skip after_success"
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: s-weigand
        password:
          secure: WX0UN8mLHfKbrSfI4ZJ9yaKMpE1OhbMhB7Eaa3HydziJT0Hlkecw2Jy/avOwpcxT2HOJzkFxNSUghr4ZanziejiSUkXjFRTIaP44gLw5LqXc+KNLPTB3keZYm6s2rxQuE2H6zOheDmaGKIh8ppyxWpAuW4noEVzCPeQTATQ7/iw5OChHjHLn7MBmBChVhO4+/EujvjYzA7Q9ZbdEcmNGKdLBCp7Oak2x4MesgCxjT5eMe0JkyEP1dGKZMtaTp9cuc6C1GwkAW4OUoAr3j9xDq744v2H+1DF4eII2s/0BNc6uhf0s+dhcvWp2juA3u3QpZ/zqEngaCr/rtKYjTMkUrPV34tpAcWajvvs/HNqlfck+jQSCkm9wa7gM5E6eLFbIKVF8dvF2AARFQh+9uxVx5LhJuMFrJdzRpxm/+rBffm8gqesb2tHQOIQwgRvg8czI4hJ5Qw6Tcs9jepTLFdMeTc/PS/LYk1uFnlhIijkO5fXxBQuwjkR4bLHBRSF1kU9zToLEPw745lmO3Q1Y4ZJmsNXqDpdA70MyEKED/KrRIn5rBia+a+tjOU3V08aX0w3VqBTAgQqhzq7HX1E2rYYAOOmI2NrLaNnZyFvbWh+bWIa1oJ6mJ6WB90f6mH2/jeB8TdLl8xHuWgHREz4L6Kwg1mmGEVdYsseWaoD5FCs55H4=
        on:
          tags: true
          branch: master
          repo: s-weigand/djangocms-equation

  allow_failures:
    #      this tests are allowed to fail since they rely external resources
    - env: TOXENV=docs-links

before_install:
  - nvm install 12
  - node --version
  - npm --version
  - nvm --version
  - ip addr show
  - printenv
  - npm i
  - npm run publish
  - docker-compose up -d
  - docker-compose ps

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - python -m pip install -U pip>=18.1
  - pip install tox-travis coveralls

# Command to run tests, e.g. python setup.py test
script: tox

after_success:
  - if [ "$DJANGO" == "2.2" ] && [ "$CMS" == "3.7" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.7" ]; then "$PWD/.tox/py37-dj21-cms36/bin/python" tests/manage.py test utils.percy_upload; fi
  - ls -la test_screenshots/Chrome
  - ls -la test_screenshots
  - coveralls
  - coverage erase
