# Config file for automatic testing at travis-ci.org
sudo: false
language: python
cache: pip

language: python
python:
  - 3.7
  - 3.6
  - 3.5
  - 2.7

env:
  - DJANGO="1.11"
  - DJANGO="2.0"
  - DJANGO="2.1"

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=flake8
      after_success:
        - echo "done"

    - python: 3.6
      env: TOXENV=docs-create
      after_success:
        - echo "done"

    - python: 3.6
      env: TOXENV=docs-links
      after_success:
        - echo "done"

    - language: python
      sudo: required
      dist: xenial
      python: "3.7"

  allow_failures:
    #      this tests are allowed to fail since they rely external resources
    - env: TOXENV=docs-links

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - python -m pip install -U pip>=18.1
  - pip install tox-travis coveralls

# Command to run tests, e.g. python setup.py test
script: tox

after_success:
    - coveralls
    - coverage erase

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: s-weigand
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: s-weigand/djangocms_equation
    python: 3.6
